AllCops:
  TargetRubyVersion: '2.3'

Style/FrozenStringLiteralComment:
  EnforcedStyle: 'never'

Style/SymbolArray:
  EnforcedStyle: 'brackets'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%w': '()'

Documentation:
  Enabled: false
